integer i = 5;
integer j = 10;
CalculatorSimple.add(i,j);

//ListDemoForLoop.iterateIntegerList();
//create a list HERE.
//and pass to the add(list)
 List<integer> listInteger = new list<integer>();
listInteger.add(15);//0
listInteger.add(21);//1
listInteger.add(10);//2
listInteger.add(15);//3
listInteger.add(15);//4
integer sum = ListDemoForLoop.add(listInteger);
system.debug('sum of list is ' + sum);